### ISSUE TITLE
Fails with MissingMethodException

### ISSUE THREAD

**Issue by sturench** [entagen/jenkins-build-per-branch#22]
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: java.util.ArrayList.findResults() is applicable for argument types: (com.entagen.jenkins.JenkinsJobManager$_findRequiredTemplateJobs_closure5) values: [com.entagen.jenkins.JenkinsJobManager$_findRequiredTemplateJobs_closure5@d964af]
Possible solutions: findResult(groovy.lang.Closure), findResult(groovy.lang.Closure), findResult(java.lang.Object, groovy.lang.Closure), findResult(java.lang.Object, groovy.lang.Closure)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:54)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at com.entagen.jenkins.JenkinsJobManager.findRequiredTemplateJobs(JenkinsJobManager.groovy:92)
	at com.entagen.jenkins.JenkinsJobManager$findRequiredTemplateJobs.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:44)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at com.entagen.jenkins.JenkinsJobManager.syncWithRepo(JenkinsJobManager.groovy:33)
	at com.entagen.jenkins.JenkinsJobManager$syncWithRepo.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.entagen.jenkins.Main.main(Main.groovy:26)

FAILURE: Build failed with an exception.

**Comment by jamesdh** [comment]
Filing bankruptcy on this. Since upgrading the groovy version in the build file we have not heard anything more. Please reopen if otherwise.
