### ISSUE TITLE
When using GitHub authentication the gradle calls get a 403

### ISSUE THREAD

**Issue by alexnederlof** [entagen/jenkins-build-per-branch#38]
When you use GitHub as an authentication platform, the calls end up witha 403.

```
[workspace] $ /var/lib/jenkins/jobs/SyncCrawljaxGitBranchesWithJenkins/workspace/gradlew -DjenkinsUrl=http://jenkins.crawljax.com -DgitUrl=git://github.com/crawljax/crawljax.git -DtemplateJobPrefix=crawljax -DtemplateBranchName=master -DnestedView=Crawljax-branches syncWithRepo
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:syncWithRepo
===============================================================
 jenkinsUrl: http://jenkins.crawljax.com
 gitUrl: git://github.com/crawljax/crawljax.git
 templateJobPrefix: crawljax
 templateBranchName: master
 nestedView: Crawljax-branches
===============================================================
executing command: git ls-remote --heads git://github.com/crawljax/crawljax.git
	209f69659e82f24131a2e7c7405231615bfa1db8	refs/heads/better-xpath-resolving
	4fa9f2958cae6703a8a07ef9b8334500ebc57e70	refs/heads/blue-monday-master
	e865cf822a7fa3d22812700e504d1f7bfda214f8	refs/heads/fix-plugin-executions
	5af558824b2f3fd43e18a52b9c2e13ae5e9bd9de	refs/heads/js-updates
	01e2e696261d91222b2325200f0ead45cb3839cf	refs/heads/master
	8bc350f78bcc65a5e6952159735b4e43be7feca4	refs/heads/meaningful-statenames
	fb0b6bfec024389334b20c61d91315d58ca2fbbe	refs/heads/new-concurrency-squashed
	09551514995f46cedabd8c37af8da7b76c1ca51a	refs/heads/web-ui-stable
getting project names from http://jenkins.crawljax.com/api/json
Creating missing job: crawljax-fullbuild-better-xpath-resolving from crawljax-fullbuild-master
Exception in thread "main" java.lang.Exception: Unexpected failure with path http://jenkins.crawljax.com/job/crawljax-fullbuild-master/config.xml, HTTP Status Code: 403, full map: [path:job/crawljax-fullbuild-master/config.xml, contentType:text/plain, headers:[Accept:application/xml]]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
	at com.entagen.jenkins.JenkinsApi.get(JenkinsApi.groovy:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:267)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at com.entagen.jenkins.JenkinsApi.getJobConfig(JenkinsApi.groovy:49)
	at com.entagen.jenkins.JenkinsApi$getJobConfig.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at com.entagen.jenkins.JenkinsApi.configForMissingJob(JenkinsApi.groovy:71)
	at com.entagen.jenkins.JenkinsApi$configForMissingJob.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
	at com.entagen.jenkins.JenkinsApi.cloneJobForBranch(JenkinsApi.groovy:55)
	at com.entagen.jenkins.JenkinsApi$cloneJobForBranch.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.entagen.jenkins.JenkinsJobManager.createMissingJobs(JenkinsJobManager.groovy:64)
	at com.entagen.jenkins.JenkinsJobManager$createMissingJobs.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at com.entagen.jenkins.JenkinsJobManager.syncJobs(JenkinsJobManager.groovy:52)
	at com.entagen.jenkins.JenkinsJobManager$syncJobs.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at com.entagen.jenkins.JenkinsJobManager.syncWithRepo(JenkinsJobManager.groovy:39)
	at com.entagen.jenkins.JenkinsJobManager$syncWithRepo.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at com.entagen.jenkins.Main.main(Main.groovy:29)
Caused by: groovyx.net.http.HttpResponseException: Forbidden
	at groovyx.net.http.RESTClient.defaultFailureHandler(RESTClient.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1047)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:914)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:877)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:508)
	at groovyx.net.http.RESTClient.get(RESTClient.java:118)
	at groovyx.net.http.RESTClient$get.call(Unknown Source)
	at com.entagen.jenkins.JenkinsApi.get(JenkinsApi.groovy:139)
	... 40 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':syncWithRepo'.
> Command '/usr/lib/jvm/java-7-openjdk-i386/bin/java' finished with (non-zero) exit value 1.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.778 secs
Build step 'Invoke Gradle script' changed build result to FAILURE
Build step 'Invoke Gradle script' marked build as failure
Finished: FAILURE
```

**Comment by maciejmakowski** [comment]
I actually have it worse, and don't even get past the retrieval of the job names:

getting project names from http://localhost:80/api/json
Exception in thread "main" org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '' with class 'groovy.util.slurpersupport.NodeChildren' to class 'java.util.List'

Does anyone have any ideas how this can be resolved?

I posted a stackoverflow question here as well:
http://stackoverflow.com/questions/28688236/cant-get-jenkins-api-access-with-token-to-work-when-github-oauth-is-enabled

**Comment by bparafina** [comment]
+1 We're using github-oauth and even with an "admin" user the error shifts to a 401 from a 403.

**Comment by erichelgeson** [comment]
I think you may be running into this issue: https://issues.jenkins-ci.org/browse/JENKINS-22346

You can try setting the system property `-D hudson.model.User.allowNonExistentUserToLogin=true`

Basicly 'admin' doesnt exist on github (or you dont own the user admin on github) so it is failing.

**Comment by bparafina** [comment]
Right -- except I'm using a github account with "admin" privs on the jenkins box. So it's still relying on the github oauth to validate the api call. With the account information (username/pass) it pushes to 401.

w/o admin:
```
getting project names from http://build.djed.com:8080/api/json
Exception in thread "main" java.lang.Exception: Unexpected failure with path http://build.djed.com:8080/api/json, HTTP Status Code: 403, full map: [path:api/json]
```

w/ admin
```
getting project names from http://build.djed.com:8080/api/json
Exception in thread "main" java.lang.Exception: Unexpected failure with path http://build.djed.com:8080/api/json, HTTP Status Code: 401, full map: [path:api/json]
```

**Comment by jamesdh** [comment]
@bparafina without having an actual local jenkins Admin account that bypasses the GitHub auth (and using @alexmordue's solution) this will not currently work. Build-per-branch does not currently support oauth tokens/authentication.

**Comment by jamesdh** [comment]
@bparafina I stand corrected. I just tested this out on an instance that I freshly setup w/ Github OAuth authentication and it works fine.

In order for it to work, you *must* set the `-DjenkinsUser` and `-DjenkinsPassword` gradle/JVM args, and since you are using GitHub OAuth and your Jenkins instance doesn't actually have it's own password, you have to first login to Jenkins and get your user token (User -> Configure -> Show API Token). That is what you need to use as your password.

Thanks to mocleiri/github-oauth-plugin#30 (which was eventually merged into master and released), Jenkins will failover to using basic auth if GitHub OAuth fails. This therefore allows the use of any Jenkins-local username/token for access. 

This isn't the most obvious so I'll see about clarifying it in the docs.
