### ISSUE TITLE
Not requiring something in the middle between prefix and branch name

### ISSUE THREAD

**Issue by nnguyen** [entagen/jenkins-build-per-branch#80]
I want to be able to create job with prefix that is almost the same as the job name (minus the branch name).  
My job name is ThisIsMyWholeJobNameAndAlsoMyPrefix-master

```
Exception in thread "main" java.lang.AssertionError: Unable to find any jobs matching template regex: ^(ThisIsMyWholeJobNameAndAlsoMyPrefix-[^-]*)-(master)$
You need at least one job to match the templateJobPrefix and templateBranchName suffix arguments. Expression: (templateJobs?.size() > 0)
	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:388)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:658)
	at com.entagen.jenkins.JenkinsJobManager.findRequiredTemplateJobs(JenkinsJobManager.groovy:108)
	at com.entagen.jenkins.JenkinsJobManager$findRequiredTemplateJobs.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at com.entagen.jenkins.JenkinsJobManager.syncWithRepo(JenkinsJobManager.groovy:37)
	at com.entagen.jenkins.JenkinsJobManager$syncWithRepo.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at com.entagen.jenkins.Main.main(Main.groovy:30)```

**Comment by elsticky** [comment]
I can't help you with your issue but I was curious how a job name should look by default? I don't know how to determine a Prefix for a job in Jenkins?

**Comment by jpaolini** [comment]
It's expecting a job name in the format: ThisIsMyWholeJobNameAndAlsoMyPrefix-JobDescription-master.  The format is Prefix-SomethingHere-branchName.  Hope this helps.
